apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-1st-instance
  labels:
    app: service-a-1st-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a-1st-instance
  template:
    metadata:
      labels:
        app: service-a-1st-instance
    spec:
      containers:
      - name: service-a-1st-instance
        image: pramodjayathirth/library:servicea-1.0
        ports:
        - containerPort: 8081
        env:
        - name: SERVICE_INSTANCE
          value: "Service A 1st Instance"

---
apiVersion: v1
kind: Service
metadata:
  name: service-a-1st-instance
spec:
  selector:
    app: service-a-1st-instance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP