version: '3.8'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config

  serviceA:
    build: ./services/serviceA
    ports:
      - "8081:8081"

  serviceB:
    build: ./services/serviceB
    ports:
      - "8082:8082"
