services:
  serviceA:
    endpoints:
      - http://service-a-service.default.svc.cluster.local:80
    loadBalancer: round-robin
  serviceB:
    endpoints:
      - http://service-b-service.default.svc.cluster.local:80
    loadBalancer: least-connections
  serviceC:
    endpoints:
      - http://localhost:8083
    loadBalancer: random
  serviceD:
    endpoints:
      - http://localhost:8084
    loadBalancer: something