services:
  serviceA:
    endpoints:
      - http://localhost:8081
    loadBalancer: round-robin
  serviceB:
    endpoints:
      - http://localhost:8082
    loadBalancer: least-connections
  serviceC:
    endpoints:
      - http://localhost:8083
    loadBalancer: random
  serviceD:
    endpoints:
      - http://localhost:8084
    loadBalancer: something